
const cu={id:1,name:'John Doe',email:'john.doe@dayflow.com',role:'HR Manager',department:'Human Resources',initials:'JD',color:'linear-gradient(135deg,#667eea 0%,#764ba2 100%)',isAdmin:true,checkedIn:false,checkInTime:null};
let emps=[
{id:1,employeeId:'EMP001',name:'John Doe',email:'john.doe@dayflow.com',role:'HR Manager',department:'Human Resources',phone:'+1 (555) 100-0001',joinDate:'2023-01-15',location:'Office',status:'offline',initials:'JD',color:'linear-gradient(135deg,#667eea 0%,#764ba2 100%)',workStatus:'Active'},
{id:2,employeeId:'EMP002',name:'Sarah Williams',email:'sarah.w@dayflow.com',role:'Senior Developer',department:'Engineering',phone:'+1 (555) 100-0002',joinDate:'2023-02-20',location:'Hybrid',status:'present',initials:'SW',color:'linear-gradient(135deg,#f093fb 0%,#f5576c 100%)',workStatus:'Active'},
{id:3,employeeId:'EMP003',name:'Mike Chen',email:'mike.chen@dayflow.com',role:'Product Manager',department:'Product',phone:'+1 (555) 100-0003',joinDate:'2023-03-10',location:'Remote',status:'on-leave',initials:'MC',color:'linear-gradient(135deg,#4facfe 0%,#00f2fe 100%)',workStatus:'Active'},
{id:4,employeeId:'EMP004',name:'Emily Rodriguez',email:'emily.r@dayflow.com',role:'UI/UX Designer',department:'Design',phone:'+1 (555) 100-0004',joinDate:'2023-04-05',location:'Office',status:'present',initials:'ER',color:'linear-gradient(135deg,#43e97b 0%,#38f9d7 100%)',workStatus:'Active'},
{id:5,employeeId:'EMP005',name:'David Kumar',email:'david.k@dayflow.com',role:'Data Analyst',department:'Analytics',phone:'+1 (555) 100-0005',joinDate:'2023-05-12',location:'Hybrid',status:'absent',initials:'DK',color:'linear-gradient(135deg,#fa709a 0%,#fee140 100%)',workStatus:'Active'}
];
const colors=['linear-gradient(135deg,#667eea 0%,#764ba2 100%)','linear-gradient(135deg,#f093fb 0%,#f5576c 100%)','linear-gradient(135deg,#4facfe 0%,#00f2fe 100%)','linear-gradient(135deg,#43e97b 0%,#38f9d7 100%)','linear-gradient(135deg,#fa709a 0%,#fee140 100%)','linear-gradient(135deg,#30cfd0 0%,#330867 100%)'];
document.addEventListener('DOMContentLoaded',()=>{renderEmployees(emps);setupEventListeners();updateUserAvatar();enforceAccessControl();});
function setupEventListeners(){document.getElementById('userAvatar').addEventListener('click',(e)=>{e.stopPropagation();document.getElementById('dropdown').classList.toggle('show');});document.addEventListener('click',()=>{document.getElementById('dropdown').classList.remove('show');});document.getElementById('searchBar').addEventListener('input',(e)=>{const t=e.target.value.toLowerCase();const f=emps.filter(emp=>emp.name.toLowerCase().includes(t));renderEmployees(f);});const form=document.getElementById('addEmployeeForm');const inputs=form.querySelectorAll('.form-input,.form-select');inputs.forEach(input=>{input.addEventListener('blur',()=>validateField(input));input.addEventListener('input',()=>{if(input.classList.contains('error')){validateField(input);}});});}
function enforceAccessControl(){if(!cu.isAdmin){document.getElementById('newEmployeeBtn').style.display='none';}}
function updateUserAvatar(){document.getElementById('userAvatar').textContent=cu.initials;}
function renderEmployees(el){const g=document.getElementById('employeeGrid');g.innerHTML='';el.forEach(e=>{const c=document.createElement('div');c.className='employee-card';c.onclick=()=>openEmployeeProfile(e);const si=getStatusIcon(e.status);c.innerHTML=`<div class="status-indicator ${e.status}">${si}</div><div class="employee-avatar" style="background:${e.color}">${e.initials}</div><div class="employee-info"><div class="employee-name">${e.name}</div><div class="employee-role">${e.role}</div><div class="employee-dept">${e.department}</div></div>`;g.appendChild(c);});}
function getStatusIcon(s){return s==='on-leave'?'✈️':'';}
function openEmployeeProfile(e){const m=document.getElementById('profileModal');const c=document.getElementById('profileContent');document.getElementById('modalTitle').textContent=e.id===cu.id?'My Profile':'Employee Profile';c.innerHTML=`<div class="profile-avatar-large" style="background:${e.color}">${e.initials}</div><div class="info-group"><div class="info-label">Full Name</div><div class="info-value">${e.name}</div></div><div class="info-group"><div class="info-label">Employee ID</div><div class="info-value">${e.employeeId}</div></div><div class="info-group"><div class="info-label">Email</div><div class="info-value">${e.email}</div></div><div class="info-group"><div class="info-label">Phone</div><div class="info-value">${e.phone||'Not provided'}</div></div><div class="info-group"><div class="info-label">Role</div><div class="info-value">${e.role}</div></div><div class="info-group"><div class="info-label">Department</div><div class="info-value">${e.department}</div></div><div class="info-group"><div class="info-label">Work Location</div><div class="info-value">${e.location}</div></div><div class="info-group"><div class="info-label">Date of Joining</div><div class="info-value">${e.joinDate}</div></div><div class="info-group"><div class="info-label">Status</div><div class="info-value">${formatStatus(e.status)}</div></div>`;m.classList.add('show');}
function formatStatus(s){const m={'present':'🟢 Present in Office','offline':'🔴 Offline','on-leave':'✈️ On Approved Leave','absent':'🟡 Absent Without Leave'};return m[s]||s;}
function openMyProfile(){openEmployeeProfile(cu);}
function closeModal(id){document.getElementById(id).classList.remove('show');}
function checkIn(){if(!cu.checkedIn){cu.checkedIn=true;cu.checkInTime=new Date();const u=emps.find(e=>e.id===cu.id);if(u){u.status='present';}updateAttendanceStatus();renderEmployees(emps);}}
function checkOut(){if(cu.checkedIn){cu.checkedIn=false;cu.checkInTime=null;const u=emps.find(e=>e.id===cu.id);if(u){u.status='offline';}updateAttendanceStatus();renderEmployees(emps);}}
function updateAttendanceStatus(){const s=document.getElementById('attendanceStatus');if(cu.checkedIn){const t=cu.checkInTime.toLocaleTimeString('en-US',{hour:'2-digit',minute:'2-digit'});s.innerHTML=`<span class="status-text">Checked in since ${t}</span><button class="btn btn-danger" onclick="checkOut()">Check Out</button>`;}else{s.innerHTML=`<span class="status-text">You are offline</span><button class="btn btn-success" onclick="checkIn()">Check In</button>`;}}
function openAddEmployeeForm(){if(!cu.isAdmin){showToast('Unauthorized: Only Admin/HR can add employees','error');return;}populateManagerDropdown();document.getElementById('addEmployeeForm').reset();document.querySelectorAll('.form-error').forEach(e=>e.classList.remove('show'));document.querySelectorAll('.form-input, .form-select').forEach(e=>e.classList.remove('error'));document.getElementById('addEmployeeModal').classList.add('show');}
function closeAddEmployeeForm(){document.getElementById('addEmployeeModal').classList.remove('show');}
function populateManagerDropdown(){const sel=document.getElementById('empManager');sel.innerHTML='<option value="">Select Manager (Optional)</option>';emps.filter(e=>e.role==='Manager'||e.role==='HR').forEach(e=>{sel.innerHTML+=`<option value="${e.id}">${e.name}</option>`;});}
function validateField(f){const id=f.id;const val=f.value.trim();const err=document.getElementById(id+'Error');let valid=true;if(f.required&&!val){valid=false;err.textContent='This field is required';}else if(id==='empEmail'){const regex=/^[^\s@]+@[^\s@]+\.[^\s@]+$/;if(!regex.test(val)){valid=false;err.textContent='Please enter a valid email';}else if(emps.some(e=>e.email.toLowerCase()===val.toLowerCase())){valid=false;err.textContent='Email already exists';}}else if(id==='empId'){if(emps.some(e=>e.employeeId.toUpperCase()===val.toUpperCase())){valid=false;err.textContent='Employee ID already exists';}}if(valid){f.classList.remove('error');err.classList.remove('show');}else{f.classList.add('error');err.classList.add('show');}return valid;}
function handleAddEmployee(e){e.preventDefault();if(!cu.isAdmin){showToast('Unauthorized: Only Admin/HR can add employees','error');return;}const form=document.getElementById('addEmployeeForm');const inputs=form.querySelectorAll('.form-input,.form-select');let allValid=true;inputs.forEach(i=>{if(!validateField(i)){allValid=false;}});if(!allValid)return;const name=document.getElementById('empName').value.trim();const email=document.getElementById('empEmail').value.trim();const eid=document.getElementById('empId').value.trim();const role=document.getElementById('empRole').value;const dept=document.getElementById('empDepartment').value;const phone=document.getElementById('empPhone').value.trim();const join=document.getElementById('empJoinDate').value;const loc=document.getElementById('empLocation').value;const stat=document.getElementById('empStatus').value;const mgr=document.getElementById('empManager').value;const notes=document.getElementById('empNotes').value.trim();const initials=name.split(' ').map(n=>n[0]).join('').toUpperCase().substring(0,2);const color=colors[emps.length%colors.length];const newEmp={id:emps.length+1,employeeId:eid,name:name,email:email,role:role,department:dept,phone:phone,joinDate:join,location:loc,status:'offline',initials:initials,color:color,workStatus:stat,manager:mgr||null,notes:notes||null};emps.push(newEmp);renderEmployees(emps);showToast('Employee added successfully');closeAddEmployeeForm();}
function showToast(msg,type='success'){const t=document.getElementById('toast');const tm=document.getElementById('toastMessage');tm.textContent=msg;t.className='toast '+(type==='error'?'error':'');t.classList.add('show');setTimeout(()=>t.classList.remove('show'),3000);}
function logout(){if(confirm('Are you sure you want to log out?')){showToast('Logging out...');setTimeout(()=>alert('In production: Redirect to login page'),1000);}}
document.getElementById('profileModal').addEventListener('click',(e)=>{if(e.target.id==='profileModal')closeModal('profileModal');});
document.getElementById('addEmployeeModal').addEventListener('click',(e)=>{if(e.target.id==='addEmployeeModal')closeAddEmployeeForm();});